//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelePomocnikWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Contact = new HashSet<Contact>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.Guid> TelemarketerId { get; set; }
    
        public virtual Telemarketer Telemarketer { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
    }
}
