//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelePomocnikWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactHistory
    {
        public System.Guid Id { get; set; }
        public string Info { get; set; }
        public System.DateTime ContactDate { get; set; }
        public System.Guid ContactId { get; set; }
        public System.Guid TelemarketerId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Telemarketer Telemarketer { get; set; }
    }
}
