//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelePomocnikWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Contact = new HashSet<Contact>();
            this.Contact1 = new HashSet<Contact>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Members { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public string MoreInfo { get; set; }
        public string Place { get; set; }
    
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Contact> Contact1 { get; set; }
    }
}
