//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelePomocnikWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MustCallInformation
    {
        public System.Guid Id { get; set; }
        public string Information { get; set; }
        public System.DateTime DateMustContact { get; set; }
        public System.Guid WhoMustContact { get; set; }
        public System.Guid ToWhoMustContact { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Telemarketer Telemarketer { get; set; }
    }
}
