//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelePomocnikWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telemarketer
    {
        public Telemarketer()
        {
            this.Company = new HashSet<Company>();
            this.Contact = new HashSet<Contact>();
            this.ContactHistory = new HashSet<ContactHistory>();
            this.MustCallInformation = new HashSet<MustCallInformation>();
            this.Telemarketer1 = new HashSet<Telemarketer>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.Guid RoleId { get; set; }
        public string FullName { get; set; }
        public System.Guid ManagerId { get; set; }
    
        public virtual ICollection<Company> Company { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<ContactHistory> ContactHistory { get; set; }
        public virtual ICollection<MustCallInformation> MustCallInformation { get; set; }
        public virtual ICollection<Telemarketer> Telemarketer1 { get; set; }
        public virtual Telemarketer Telemarketer2 { get; set; }
    }
}
